package com.app.revfoodsbackend.model;

import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.Hibernate;

import com.fasterxml.jackson.annotation.JsonIgnore;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@ApiModel
@Getter
@Setter
@RequiredArgsConstructor
@Entity
@Table
@AllArgsConstructor
@ToString
public class Help {
	@ApiModelProperty(value = "This is the auto generated help Id")
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int helpId;
	@ApiModelProperty(value = "This is for help generated by customer")
	private String help;
	@ApiModelProperty(value = "This is for the status of help")
	private boolean helpStatus;

	@JsonIgnore
	@ManyToOne
	@JoinColumn(name = "supervisorId", referencedColumnName = "supervisorId")
	private Supervisor supervisor;

	@OneToOne(mappedBy = "help", cascade = CascadeType.ALL)
	private Customer customer;

	@Override
	public boolean equals(Object o) {
		if (this == o)
			return true;
		if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o))
			return false;
		Help help = (Help) o;
		return Objects.equals(helpId, help.helpId);
	}

	@Override
	public int hashCode() {
		return 0;
	}
}
